### ISSUE TITLE
docker-compose.yaml

### ISSUE THREAD

**Issue by evabronskayaa** [IvanSvyatykh/SemestrDatabaseWork#3]
Внутренние порты тоже лучше выносить в .env

```yaml
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
```
